### ISSUE TITLE
fix alignment of words "indigestaque moles nec" in Ovid Met lines 7-8

### ISSUE THREAD

**Issue by monzug** [alpheios-project/cts-texts-latinLit#2]
tested in Safari and Chrome, go to https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0959.phi006.alpheios-text-lat1/passage/1.1-1.30, nec is line 8
see screenshots
nec in recent build (also adjective and noun have beed included)
![Screen Shot 2020-06-12 at 2 58 32 PM](https://user-images.githubusercontent.com/41396793/84505170-8c3fa880-acbd-11ea-9933-6f5d32ded2ae.png)

nec in the release diagram (conjunction and adverb)
![Screen Shot 2020-06-12 at 2 59 56 PM](https://user-images.githubusercontent.com/41396793/84505193-9792d400-acbd-11ea-964d-c28037840a5a.png)

**Comment by balmas** [comment]
the data has been updated and verified.
